[package]
name = "pyroclast"
version = "0.1.0"
edition = "2024"
default-run = "pyroclast"

[[bin]]
name = "pyroclast"
path = "src/main.rs"

[[bin]]
name = "cargo-pyroclast"
path = "src/bin/cargo_pyroclast.rs"

[dependencies]
addr2line = { version = "0.26.1", path = "vendor/addr2line" }
blake3 = "1"
cargo_metadata = "0.23"
clap = { version = "4", features = ["derive"] }
framehop = "0.16.0"
framehop-object = "0.2.0"
gimli = "0.33.0"
hashbrown = "0.17.1"
inferno = "0.12.7"
memchr = "2"
memmap2 = "0.9.11"
object = "0.39.1"
quick-xml = "0.41"
rustc-hash = "2.1.2"
roxmltree = "0.21"
smallvec = "1.15.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
signal-hook = "0.3"
tempfile = "3"

[dev-dependencies]
object = { version = "0.39.1", features = ["build"] }
proptest = "1.11.0"

[profile.release]
debug = false
strip = true
lto = "thin"
codegen-units = 1
overflow-checks = true

[profile.profiling]
inherits = "release"
debug = 2
strip = false
